// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjnqafuitztrnoextulz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqbnFhZnVpdHp0cm5vZXh0dWx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNzQxMzYsImV4cCI6MjA1NTY1MDEzNn0.sM1KzUpGh5LQe_wiqgCvuaYKm2e2BjQRgWxD5eV3qhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);